version: '3.5'

services:
  nginx:
     image: nginx:latest
     container_name: nginx-proxy
     ports:
       - "80:80"
     volumes:
      - ./conf.d/embedding.conf:/etc/nginx/conf.d/embedding.conf:ro
     depends_on:
       - express-app
     networks:
       - milvus-net
     restart: always 