FROM node:18

WORKDIR /app

COPY package*.json ./
COPY tsconfig.json ./

RUN npm install

# Don't need nodemon anymore since ts-node-dev handles it
# RUN npm install nodemon -g

COPY . .

EXPOSE 3000

# Development
CMD ["npm", "run", "dev"] 