version: "3.8"

services:
  # Express API Application (for local development only)
  express-app:
    container_name: lumen-express-app
    build:
      context: .
      dockerfile: Dockerfile.express
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./logs:/app/logs
      - ./prisma:/app/prisma
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    restart: unless-stopped
    command: >
      sh -c "npx prisma generate && npm run dev"

    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
