import * as dotenv from "dotenv";
dotenv.config();

export const ENV = {
  NODE_ENV: process.env.NODE_ENV,
  EMBEDDING_MODEL: process.env.EMBEDDING_MODEL,
  INFERENCE_PROVIDER: process.env.INFERENCE_PROVIDER,
  HUGGING_FACE_API_TOKEN: process.env.HUGGING_FACE_API_TOKEN,
  PORT: process.env.PORT || "3000",
  MILVUS_ADDRESS: process.env.MILVUS_ADDRESS,
  MILVUS_USERNAME: process.env.MILVUS_USERNAME,
  MILVUS_PASSWORD: process.env.MILVUS_PASSWORD,
  WP_API_URL: process.env.WP_API_URL,
  WP_USE_CUSTOM_ENDPOINT: process.env.WP_USE_CUSTOM_ENDPOINT,
  WP_USER_USERNAME: process.env.WP_USER_USERNAME,
  WP_USER_PASSWORD: process.env.WP_USER_PASSWORD,
  THRESHOLD: process.env.THRESHOLD,
  JWT_SECRET: process.env.JWT_SECRET!,
  JWT_TTL: process.env.JWT_TTL!,
  RATE_LIMIT_WINDOW_MS: parseInt(process.env.RATE_LIMIT_WINDOW_MS!),
  RATE_LIMIT_MAX: parseInt(process.env.RATE_LIMIT_MAX!),
  RECAPTCHA_SECRET: process.env.RECAPTCHA_SECRET!,
  RECAPTCHA_THRESHOLD: parseFloat(process.env.RECAPTCHA_THRESHOLD!),
  CORS_ORIGIN_DEV: process.env.CORS_ORIGIN_DEV!,
  CORS_ORIGIN_TEST: process.env.CORS_ORIGIN_TEST!,
  CORS_ORIGIN_PROD: process.env.CORS_ORIGIN_PROD!,
  CORS_ORIGIN_STAGING: process.env.CORS_ORIGIN_STAGING!,
  SERVER_API_KEY: process.env.SERVER_API_KEY!,
};
